name: Docker Image CI

on:
  push:
    branches: 
      - "main"
      - "*"
      
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Tag
        run: echo "::set-output name=tag::$(if [ $GITHUB_REF = 'refs/heads/main' ]; then echo latest; else echo $GITHUB_REF | sed 's#refs/heads/##'; fi)"

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: /win10-enterprise/.
          tags: moraloco/vm-in-docker:${{ steps.set-tag.outputs.tag }}
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
