name: Docker CI Win 10 Enterprise

on:
  push:
    branches: 
      - "main"
      - "*"
      
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set tag output
        run: |
          if [ "$GITHUB_REF" = "refs/heads/main" ]; then
            echo "tag=latest" >> $GITHUB_ENV
          else
            tag=$(echo "$GITHUB_REF" | sed 's#refs/heads/##')
            echo "tag=$(echo "$GITHUB_REF" | sed 's#refs/heads/##')" >> $GITHUB_ENV
          fi

      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./win10-enterprise
          push: true
          tags: moraloco/vm-in-docker:win10-enterprise-${{ env.tag }}
